'use client';

import { useState, useEffect, useMemo } from 'react';
import Link from 'next/link';
import Nav from '@/components/Nav';
import { getGallery } from '@/lib/api';
import { GalleryItem } from '@/types';

const CONFIDENCE_CLASS: Record<string, string> = {
  High:   'sig-confidence-badge sig-confidence-high',
  Medium: 'sig-confidence-badge sig-confidence-medium',
  Low:    'sig-confidence-badge sig-confidence-low',
};

const MODES = ['all', 'quick', 'standard', 'deep'] as const;
type ModeFilter = typeof MODES[number];

function ReportCard({ item }: { item: GalleryItem }) {
  const badgeClass = CONFIDENCE_CLASS[item.confidence_level ?? ''] ?? CONFIDENCE_CLASS.Medium;
  return (
    <Link href={`/report/${item.job_id}`} className="sig-report-card">
      <div className="sig-report-card-header">
        <p className="sig-report-card-title">{item.query}</p>
        {item.confidence_level && (
          <span className={badgeClass}>{item.confidence_level}</span>
        )}
      </div>
      {item.first_finding && (
        <p className="sig-report-card-finding">{item.first_finding}</p>
      )}
      <p className="sig-report-card-meta">
        {item.mode.toUpperCase()} · {item.source_count} source{item.source_count !== 1 ? 's' : ''} · {new Date(item.created_at).toLocaleDateString([], { year: 'numeric', month: 'short', day: 'numeric' })}
      </p>
    </Link>
  );
}

function SkeletonCard() {
  return (
    <div className="sig-skeleton-card">
      <div className="sig-skeleton-line" style={{ height: '18px', width: '55%' }} />
      <div className="sig-skeleton-line" style={{ height: '13px', width: '90%' }} />
      <div className="sig-skeleton-line" style={{ height: '13px', width: '70%' }} />
      <div className="sig-skeleton-line" style={{ height: '11px', width: '35%', marginTop: 'auto' }} />
    </div>
  );
}

export default function GalleryPage() {
  const [items, setItems] = useState<GalleryItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [fetchError, setFetchError] = useState<string | null>(null);
  const [search, setSearch] = useState('');
  const [modeFilter, setModeFilter] = useState<ModeFilter>('all');

  useEffect(() => {
    getGallery(50)
      .then((data) => {
        setItems(Array.isArray(data) ? data : []);
        setFetchError(null);
      })
      .catch((err) => {
        setFetchError(err instanceof Error ? err.message : 'Failed to load gallery');
        setItems([]);
      })
      .finally(() => setLoading(false));
  }, []);

  const filtered = useMemo(() => {
    return items.filter((item) => {
      const matchesSearch = !search || item.query.toLowerCase().includes(search.toLowerCase());
      const matchesMode = modeFilter === 'all' || item.mode === modeFilter;
      return matchesSearch && matchesMode;
    });
  }, [items, search, modeFilter]);

  return (
    <div style={{ background: 'var(--bg-base)', minHeight: '100vh' }}>
      <Nav />
      <div className="sig-gallery-page">
        <h1 className="sig-gallery-title">Intelligence Gallery</h1>
        <p className="sig-gallery-subtitle">Browse research reports generated by SIGNAL.</p>

        {/* Filters */}
        <div className="sig-gallery-filters">
          <input
            type="text"
            className="sig-search-input"
            placeholder="Search reports..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
          <div className="sig-gallery-mode-row">
            {MODES.map((m) => (
              <button
                key={m}
                type="button"
                onClick={() => setModeFilter(m)}
                className={`sig-mode-btn${modeFilter === m ? ' sig-mode-active' : ''}`}
              >
                {m === 'all' ? 'All' : m}
              </button>
            ))}
          </div>
        </div>

        {/* Grid */}
        {loading ? (
          <div className="sig-gallery-grid">
            {[0, 1, 2, 3, 4, 5].map((i) => <SkeletonCard key={i} />)}
          </div>
        ) : filtered.length === 0 ? (
          <div className="sig-gallery-empty">
            <span style={{ fontFamily: 'var(--font-mono)', fontSize: '24px', color: 'var(--text-tertiary)' }}>◈</span>
            <p style={{ fontFamily: 'var(--font-mono)', fontSize: '13px', color: 'var(--text-tertiary)' }}>
              {fetchError
                ? fetchError
                : items.length === 0
                  ? 'No reports yet.'
                  : 'No reports match your filters.'}
            </p>
            {items.length === 0 && !fetchError && (
              <>
                <p style={{ fontFamily: 'var(--font-mono)', fontSize: '11px', color: 'var(--text-tertiary)', letterSpacing: '0.05em' }}>
                  Run your first research to populate the gallery.
                </p>
                <Link href="/research" className="sig-cta-primary" style={{ marginTop: '8px' }}>
                  Start Researching →
                </Link>
              </>
            )}
          </div>
        ) : (
          <div className="sig-gallery-grid">
            {filtered.map((item) => <ReportCard key={item.job_id} item={item} />)}
          </div>
        )}
      </div>
    </div>
  );
}
